### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by JohannesCox** [ShihaoXu/Go-App#4]
Wir sollten in unserem Pflichtenheft noch erwähnen, dass es garantiert sein muss, dass keine Standorte von Einzelpersonen angezeigt werden können. Sollte zu Nichtfunktoinalen Anforderungen gehören.

**Comment by eggpainhorse** [comment]
Ich habe in NFA den Datenschutz schon geschrieben,aber nicht sehr ausfuehrlich

**Comment by JohannesCox** [comment]
Da geht es ja aber nur um die Verschlüsselung der Datenkommunikation und nicht um das Anonymisieren der Standorte oder ?

**Comment by eggpainhorse** [comment]
Also,genau,es geht nur um die Verschlüsselung der Datenkommunikation

**Comment by ShihaoXu** [comment]
Nach dem Betreuer ist es zugelassen, den Standort von Einzelpersonen anzuzeigen, sobald der Standort nicht mit den personenbezogenen Daten auf der Karte beschriftet ist.

**Comment by JohannesCox** [comment]
Hattest nochmal mit unserem betreuer deswegen gesprochen? Weil wenn ich mich richtig erinnere,  hatte er doch das letzte mal gesagt, dass die Gruppe mindestens 2-3 personen haben muss, um angezeigt werden zu dürfen. Stichwort: KSC Fan der alleine ins Stadion oder in den Fanshop geht, sodass für die anderen Mitglieder der Veranstaltung offensichtlich ist, um welche Person es sich handelt.

**Comment by ShihaoXu** [comment]
Habe nicht nochmal mit ihm besprochen. Erinnere ich mich richtig, gibt er nur Alternativen. Die Entscheidung liegt bei uns. Wir können heute nochmal danach fragen.
