### ISSUE TITLE
Nicht lokal kompilierbare Latex Datei und einige Probleme.

### ISSUE THREAD

**Issue by ShihaoXu** [ShihaoXu/Go-App#5]
Hi Leute,

Ich versuchte meine Bilder in bestehenden Dateien zu integrieren. Aber bei mir ist etwas schief gelaufen und dazu geführt, dass ich die Pflichtenheft.tex Datei nicht kompilieren kann. Später werde ich das Problem lösen, aber nun möchte ich einige Vorschläge sowie Probleme in exsitierenden Dateien auflisten. 

- [x] Jeweilige Section könnte neue Seite besitzen. 
- [x] Die Auflösung der Bilder könnte an das Layout angepasst werden.
- [x] Bei "Nicht-Funktionale Anforderungen" und "Globale Testfälle" fehlt die Gliederung.
- [x] Szenario Nr. 5 sollte unter subsubsection stehen. Jetzt ist das unter subsection.
- [x] im Abschnitt 9.4.1 und Beschreibung von Abbildung 4 tretten einige Anführungszeichen-Fehler ein. `` bzw. ''(doppelt backtick bzw. doppelt Apostroph" sollten als englische Anführungszeichen genutzt werden. \glqq{} bzw. \grqq{} für deutsche Anführungszeichen.
- [x] Über grobe Gliederung bei "Globale Testfaelle", und "globaleTestfaelle_new.tex" brauchen wir noch zu besprechen und ersetzen nach Diskussion die ursprüngliche Fassung mit der aktuellen.

Ich lade die Anwendungsfalldiagramme gleich hoch.

**Comment by Martin9295** [comment]
Habe bei "Globale Testfälle" eine grobe Gliederung erstellt. Die aktuelle Version findet ihr momentan unter "globaleTestfaelle_neu.tex". Wenn ihr mit den Änderungen einverstanden seid, kann die ursprüngliche Fassung mit der aktuellen ersetzt werden. 

Der Fehler bei Szenario Nr.5 ist bisher zumindest in der zugehörigen .tex -Datei behoben, genauso wie die Anführungszeichen-Fehler innerhalb der Abbildungsbeschreibungen.

**Comment by ShihaoXu** [comment]
Danke für die Fehlerbehebung. Habe die bisherigen Probleme aktualisiert und es in obigen TODO hinzugefügt.
