### ISSUE TITLE
0,- Aufgaben

### ISSUE THREAD

**Issue by ShihaoXu** [ShihaoXu/Go-App#6]
- [x] GUI - Alle Notifikationen stumm schalten
- [x] GUI - Glossar generell bearbeiten
- [x] Zielbestimmung - Wann Push-Notifikation? 
- [x] Globale Testfaelle ersetzen.
- [x] Nicht Funktionale Anforderungen, Zielgruppe fehlt. 
- [x] AD - Veranstaltung - PushUpNotifikation komnentieren
- [x] AD - Benutzerdaten - Streichen
- [x] AD - System - Veranstaltung stumm schalten veraedern.
- [x] Zeilenumbruch, FA/NFA/TF Stil
- [x] NFA Anzahl der Veranstaltung beschränken
- [ ] Einleitung überarbeiten.
- [ ] Produkteinsatz Gleiderung ändern und ggf überarbeiten.
- [ ] Nichtfunktionale Anforderungen: Reaktionszeit etc.
- [ ] Testfall: Internetverbindung bricht ab
- [x] Szenarien: Mitglied löschen entfernen
- [x] Szenarien: Namen geben.
- [x] AD: Go funktion umbennen zu VA starten/stoppen
- [ ] Titelseite: Betreuernamen fehlen.

**Comment by JohannesCox** [comment]
Ich habe die NF anforderungen etwas überarbeitet. Bin aber bei der ganzen Reaktionszeit-Problematik immer noch ratlos. Ich denke wir könnte das ganze aber notfalls auch so abschicken.

**Comment by ShihaoXu** [comment]
Meinst du, dass wir präzise Testbarkeit dafür auch mitgeben, oder?
